# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 9 * * 1"}] # every Mon at 9:00 UTC
  workflow_dispatch:
  push: {branches: ["main"]} # run workflow manually and on each commit
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kares
          template: classic
          config_display: large
          #template: markdown
          #filename: metrics-generated.md
          #config_output: markdown
          base: repositories
          base_indepth: yes
          repositories: 300
          repositories_affiliations: owner, collaborator, organization_member
          #commits_authoring: kares
          config_timezone: Europe/Zurich
          repositories_skipped: |
            kares/kares
          #
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_ignored: worker, follower, deployer, chatter, verified, automator
          #
          plugin_lines: yes
          plugin_lines_history_limit: 0
          plugin_lines_repositories_limit: 300
          plugin_lines_sections: history
          plugin_lines_delay: 15
          #
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes
          #
          plugin_habits: no
          plugin_habits_from: 3000
          plugin_habits_charts_type: classic
          plugin_habits_days: 90
          plugin_habits_facts: yes
          plugin_habits_languages_limit: 12
          #
          plugin_introduction: yes
          plugin_introduction_title: yes
          #
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_details: percentage
          #
          plugin_notable: no
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
