# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (at the end of every day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kares
          template: classic
          base: repositories, metadata
          config_timezone: Europe/Zurich
          repositories_skipped: |
            kares/kares
          plugin_achievements: yes
          plugin_lines: yes
          plugin_lines_history_limit: 0
          plugin_lines_repositories_limit: 30
          plugin_lines_sections: base, repositories, history
          plugin_lines_delay: 10 # seconds
          plugin_followup: yes
          plugin_followup_sections: repositories
          #plugin_followup_indepth: yes
          plugin_habits: no
          plugin_habits_from: 3000
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_languages_limit: 8
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_details: count, percentage
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
